In [1]:
import numpy as np

In [3]:
np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.full((3, 3), True, dtype=bool) #create a boolean array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # extract all odd no
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# replace all odd no in arr with -1

In [10]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Replace all odd no in arr with -1 without changing ar

In [12]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Get the common items between a and b

In [15]:

np.intersect1d(a,b)

array([2, 4])

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9]) ## From 'a' remove all of 'b

In [17]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Get the positions where elements of a and b match

In [19]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

In [20]:
a = np.array([2, 6, 1, 9, 10, 3, 27]) #Get all items between 5 and 10 from a.

In [22]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr = np.arange(9).reshape(3,3)
arr         # Swap columns 1 and 2 in the array arr.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr = np.arange(9).reshape(3,3)
arr[::-1]
#reverse the rows of a 2D array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [26]:
np.arange( 0, 2, 0.3 )   ## it accepts float arguments and  create sequences of numbers

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a
#Limit the number of items printed in  python numpy array ato a maximum of 6 elements.

array([ 0,  1,  2, ..., 12, 13, 14])

In [38]:
np.set_printoptions(threshold=15)
a = np.arange(15)
a
#Print the full numpy array a without truncating

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr       #Compute the counts of unique values row-wise.

array([[ 9,  9,  4, ...,  3,  6,  3],
       [ 3,  3,  2, ..., 10,  7,  3],
       [ 5,  2,  6, ...,  8,  2,  2],
       [ 8,  8,  1, ...,  3,  6,  9],
       [ 2,  1,  8, ...,  3,  6,  2],
       [ 9,  2,  6, ...,  6,  1, 10]])

In [40]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)  #Create the ranks for the given numeric array a

[ 9  4 15  0 17 16 17  8  9  0]


In [42]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

#Create a rank array of the same shape as a given numeric array a

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [43]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a  #Compute the maximum for each row in the given array

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [44]:
a = np.array([2 , 1 ,9],float)
a.min()

1.0

In [45]:
a.max()

9.0